Fix test in stock_available
The test creates 2 product.product on the same product.template,
which is illegal if they don't have different attribute values.

No error is raised, unless another modules runs a "flush", which
does the INSERT in database and fails with:

psycopg2.IntegrityError: duplicate key value violates unique constraint "product_product_combination_unique"
DETAIL:  Key (product_tmpl_id, combination_indices)=(31, ) already exists.